"""shop and service tables

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op

import support_agent.db

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=80), nullable=False),
        sa.Column(
            "grade",
            sa.Enum(
                "normal", "vip", name="customer_grade", native_enum=False, create_constraint=True, length=30
            ),
            nullable=False,
        ),
        sa.Column("joined_at", support_agent.db.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_table(
        "customer_addresses",
        sa.Column("id", sa.String(length=30), nullable=False),
        sa.Column("customer_id", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=20), nullable=False),
        sa.Column("recipient", sa.String(length=40), nullable=False),
        sa.Column("postal_code", sa.String(length=10), nullable=False),
        sa.Column("address", sa.String(length=200), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_customer_addresses_customer_id_customers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_addresses")),
    )
    op.create_table(
        "handoffs",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("customer_id", sa.String(length=20), nullable=True),
        sa.Column(
            "reason",
            sa.Enum(
                "customer_request",
                "out_of_scope",
                "cannot_verify",
                name="handoff_reason",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("created_at", support_agent.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_handoffs_customer_id_customers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_handoffs")),
    )
    op.create_table(
        "product_variants",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("product_id", sa.String(length=20), nullable=False),
        sa.Column("option_label", sa.String(length=60), nullable=False),
        sa.Column("price_won", sa.Integer(), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_product_variants_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_variants")),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("customer_id", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "paid",
                "preparing",
                "shipped",
                "delivered",
                "cancelled",
                name="order_status",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("ordered_at", support_agent.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("items_won", sa.Integer(), nullable=False),
        sa.Column("shipping_fee_won", sa.Integer(), nullable=False),
        sa.Column("discount_won", sa.Integer(), nullable=False),
        sa.Column("total_won", sa.Integer(), nullable=False),
        sa.Column("ship_address_id", sa.String(length=30), nullable=False),
        sa.Column("ship_recipient", sa.String(length=40), nullable=False),
        sa.Column("ship_postal_code", sa.String(length=10), nullable=False),
        sa.Column("ship_address", sa.String(length=200), nullable=False),
        sa.Column("cancelled_at", support_agent.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column(
            "cancel_reason",
            sa.Enum(
                "changed_mind",
                "ordered_by_mistake",
                "delivery_too_slow",
                name="cancel_reason",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_orders_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["ship_address_id"],
            ["customer_addresses.id"],
            name=op.f("fk_orders_ship_address_id_customer_addresses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_table(
        "coupons",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("customer_id", sa.String(length=20), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "promo",
                "compensation",
                name="coupon_kind",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("amount_won", sa.Integer(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "delivery_delay",
                "defective_item",
                name="compensation_reason",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=True,
        ),
        sa.Column("order_id", sa.String(length=20), nullable=True),
        sa.Column("issued_at", support_agent.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", support_agent.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("used_at", support_agent.db.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_coupons_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_coupons_order_id_orders")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupons")),
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.String(length=20), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.String(length=20), nullable=False),
        sa.Column("product_name", sa.String(length=80), nullable=False),
        sa.Column("option_label", sa.String(length=60), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_won", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ordered",
                "cancelled",
                "return_requested",
                "exchange_requested",
                name="item_status",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_order_items_order_id_orders")),
        sa.ForeignKeyConstraint(
            ["variant_id"], ["product_variants.id"], name=op.f("fk_order_items_variant_id_product_variants")
        ),
        sa.PrimaryKeyConstraint("order_id", "line_no", name=op.f("pk_order_items")),
    )
    op.create_table(
        "payments",
        sa.Column("order_id", sa.String(length=20), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "card",
                "bank_transfer",
                "simple_pay",
                name="payment_method",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("amount_won", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "paid",
                "refund_pending",
                "refunded",
                name="payment_status",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("refund_won", sa.Integer(), nullable=False),
        sa.Column("paid_at", support_agent.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_payments_order_id_orders")),
        sa.PrimaryKeyConstraint("order_id", name=op.f("pk_payments")),
    )
    op.create_table(
        "service_requests",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("order_id", sa.String(length=20), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "return",
                "exchange",
                name="request_kind",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "reason",
            sa.Enum(
                "changed_mind",
                "defective",
                "wrong_item",
                name="request_reason",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("refund_won", sa.Integer(), nullable=False),
        sa.Column("return_fee_won", sa.Integer(), nullable=False),
        sa.Column("created_at", support_agent.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_service_requests_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_requests")),
    )
    op.create_table(
        "shipments",
        sa.Column("order_id", sa.String(length=20), nullable=False),
        sa.Column("carrier", sa.String(length=40), nullable=False),
        sa.Column("tracking_no", sa.String(length=30), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ready",
                "in_transit",
                "delivered",
                name="shipment_status",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("shipped_at", support_agent.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", support_agent.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("promised_by", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_shipments_order_id_orders")),
        sa.PrimaryKeyConstraint("order_id", name=op.f("pk_shipments")),
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("customer_id", sa.String(length=20), nullable=False),
        sa.Column("order_id", sa.String(length=20), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "delivery",
                "refund",
                "product",
                "account",
                "other",
                name="ticket_category",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", support_agent.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_tickets_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_tickets_order_id_orders")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
    )
    op.create_table(
        "service_request_items",
        sa.Column("request_id", sa.String(length=40), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("exchange_variant_id", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["exchange_variant_id"],
            ["product_variants.id"],
            name=op.f("fk_service_request_items_exchange_variant_id_product_variants"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.id"],
            name=op.f("fk_service_request_items_request_id_service_requests"),
        ),
        sa.PrimaryKeyConstraint("request_id", "line_no", name=op.f("pk_service_request_items")),
    )
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", support_agent.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", support_agent.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("turns", sa.Integer(), nullable=False),
        sa.Column("verified_customer_id", sa.String(length=20), nullable=True),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_sessions")),
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", support_agent.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("tool", sa.String(length=64), nullable=False),
        sa.Column("args", sa.JSON(), nullable=False),
        sa.Column("customer_id", sa.String(length=20), nullable=True),
        sa.Column("refund_won", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("decided_at", support_agent.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=64), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["chat_sessions.id"], name=op.f("fk_approvals_session_id_chat_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(op.f("ix_approvals_session_id"), "approvals", ["session_id"], unique=False)
    op.create_index(op.f("ix_approvals_status"), "approvals", ["status"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("at", support_agent.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["chat_sessions.id"], name=op.f("fk_audit_events_session_id_chat_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_kind"), "audit_events", ["kind"], unique=False)
    op.create_index(op.f("ix_audit_events_session_id"), "audit_events", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_events_session_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_kind"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_approvals_status"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_session_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_table("chat_sessions")
    op.drop_table("service_request_items")
    op.drop_table("tickets")
    op.drop_table("shipments")
    op.drop_table("service_requests")
    op.drop_table("payments")
    op.drop_table("order_items")
    op.drop_table("coupons")
    op.drop_table("orders")
    op.drop_table("product_variants")
    op.drop_table("handoffs")
    op.drop_table("customer_addresses")
    op.drop_table("products")
    op.drop_table("customers")
    # ### end Alembic commands ###
